- evil-surround.el
Not a crucial edit, but I stumbled upon `evil-apply-on-block` and thought `evil-surround-block` would be much simpler with it. I've ensured it maintains parity with vim-surround, and works at least as well as the old function.
EDIT: Turns out this refactor fixes a couple edge cases with column-surrounding to EOL.
> Refactor evil-surround-block

- evil-surround.el
When surrounding a set of lines (using a command like 'Vjjs{' in
cc-mode, for example), only the first line was correctly indented. This
commit fixes evil-surround-region so that all the selected lines are
properly indented after being surrounded.
> Fix indentation of surrounded lines

- evil-surround.el
Linewise surrounds now behave more like vim-surround:
1. Leading (and trailing) whitespace are ignored
2. Indentation is unchanged if performed on a single line
3. Multiline surrounds are reindented
4. Point is left at overlay-start rather than overlay-end after surround
My rudimentary tests pass, but I'd appreciate if anyone would help test this some more!
> Fix #52, #39, and #5 (linewise surrounding)

- evil-surround.el
When performing a block surround with a pair that is defined as a function (such as `(?< . evil-surround-read-tag)`) evil-surround will prompt the user for the tag on every line. This patch fixes that.
> Fix repetitive prompts with function pairs in block surrounds

- evil-surround.el
See #71. Side-note: this fix improves parity with vim-surround.
> Visual linewise surround fix (Fix #71)

- evil-surround.el
I wrapped ys/yS operators with raw record commands, because they
are handled by evil-yank operator, that is marked as not repeatable. Fixes #24.
> Fix repeat action (.) for ys and yS operators.

- evil-surround.el
`evil` is required for the package to be installed.
> Add missing evil package dependency

- evil-surround.el
Use evil’s facilities for reading keys from the keyboard, so that key
translations are correctly applied. Change all commands that read keys
that end up in the buffer as visible text to use the ``<C>`` interactive
spec (instead of ``c``) and ``evil-read-key`` (instead of ``read-char``).
> Use evil helpers for correct key translation

- README.md
- evil-surround.el
The commit messages include more detail.
> Escape a backtick in markdown and fix the keywords on MELPA

- evil-surround.el
A plain autoload cookie does not work correctly for functions defined
with evil-define-command, since that depends on evil being loaded, which
is not the case when the autoload file is process during Emacs startup.
Fixes #82.
> Add explicit autoload definitions to avoid implicit evil dependency

- README.md
- evil-surround.el
Evil is no longer hosted on Gitorious. This repository is apparently the
new official repository for Evil, since it is hosted under Frank
Fischer’s account, and Evil’s page on the Emacs wiki[1] points to the
wiki of this repository as being Evil’s home page.
[1] https://www.emacswiki.org/emacs/Evil
> Point to new repository for Evil

- evil-surround.el
this fixes #84, which is a replay of #24, brought back thanks to commit #66b8f89
could the maintainer review? thanks.
> fix #84: dot operator works again. reverts 66b8f89 which reintroduced #24 as a regression

- evil-surround.el
this fixes the `:type` specification for `evil-surround-pairs-alist` so that the customize interface can do something sensible with it. (partial) screenshot after applying this fix:
> Fix defcustom type specification for pairs-alist variable

- evil-surround.el
- test/evil-surround-test.el
This PR adds the the `Examples` from the readme as unit tests, all but the last one. I couldn't get the last one working. Here's what I tried in case someone wants to pick it up.
```
(evil-test-buffer
:visual-start nil
:visual-start nil
"<em>Hello</em> world!"
("VS<p class=\"important\">")
"<p class=\"important\">\n<em>Hello</em> world!\n</p>")
```
The issue has something to do with `evil-test-buffer` using `<` and `>` as visual selection.
Still, even without the last one, I think this is a good addition to the test suite.
> Add examples from readme as automated tests

- evil-surround.el
- test/evil-surround-test.el
- test/make-test.el
When motion is 'word' and evil-want-change-word-to-end is t, re-run
the motion with `evil-this-operator` explicitly set to
`evil-surround-region`
> Surround word should behave like 'ce', not 'cw'

- evil-surround.el
Before this change, there were two groups for this package in the
customize interface. The customizable variables show up in the group
named ‘surround’, while the mode itself shows up in the group named
‘evil-surround’. This is confusing and unnecessary.
To address this, put everything inside the ‘evil-surround’ group,
which is the same approach used by many other evil-mode extension
packages.
> Use ‘evil-surround’ as :group for customizable variables

- evil-surround.el
Emacs 26 saves this-command-keys across read-from-minibuffer, so make sure
this-command-keys is cleared when we record it before read-from-minibuffer.
Fixes #131
> Fix regression for Emacs 26 caused by #125 fix

- evil-surround.el
- test/evil-surround-test.el
fix a byte-compile warning too.
> surround-function improvement for lisp modes

- evil-surround.el
- test/evil-surround-test.el
In operator state the buffer is narrowed to the current Emacs field. This narrowing becomes visible when waiting for user input which is quite disruptive of the workflow. This patch widens the buffer before reading a character to avoid this.
For some context see https://github.com/emacs-evil/evil/issues/294 and https://gitorious.org/evil/cofis-evil/commit/bcf0bac?p=evil:cofis-evil.git;a=blobdiff;f=evil-types.el;h=3d963fb271013319566e923cde210af616369e0c;hp=b850569f868e994cb04236fb0f1ce614d230a722;hb=bcf0bac;hpb=ef4f5b8a74199731b08e0737027d7cb92c9e2a77.
> Fix visible narrowing when surrounding within a field

- evil-surround.el
- test/evil-surround-test.el
Closes #150.
From Vim Surround for reference:
> If t or < is used, Vim prompts for an HTML/XML tag to insert.  You may specify
> attributes here and they will be stripped from the closing tag. **If replacing a
> tag, its attributes are kept in the new tag. End your input with > to discard
> the those attributes.** If \<C-T> is used, the tags will appear on lines by
> themselves.
> optionally keep xml attributes

- evil-surround.el
- test/evil-surround-test.el
To make repeating tag changes work properly, we need to record the output from the reading the new tag.
Addresses #161
> Fix repeating tag changes

- evil-surround.el
- readme.org
- test/evil-surround-test.el
From #164.
Adds `evil-surround-local-(inner|outer)-text-object-map-list`, a buffer-local list of keymaps that contain the inner and outer text objects one wants to add to `evil-surround`. Also adds tests to make sure this works, and documentation on this in the readme.
I was a bit conflicted on making `evil-surround-local-(inner|outer)-text-object-map-list` a list, but this makes sense, as it lets you separate text objects from different minor modes. 
I also wanted to include a test that that makes sure that the text object saved to e.g. `evil-visual-state-local-map` was in fact local and did not get carried over, but I couldn't catch the error of a keybinding that isn't bound to anything in `ert`. This however is not directly related to `evil-surround` so it's probably not important …
> Add surround text objects from local keymap

- evil-surround.el
Activating evil-surround in special-mode (i.e. read-only) buffers does not make
sense. Furthermore, the bindings can overwrite bindings in modes like
magit-diff-mode (see
https://github.com/syl20bnr/spacemacs/issues/15448#issuecomment-1090810486).
This commit limits the 'globally activated modes' to text-mode and prog-mode via
the `define-globalized-minor-mode` its
[:predicate](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html#index-define_002dglobalized_002dminor_002dmode]
keyword.
As this should be the default behavior, it is not essential to change the
documentation.
> Limit global activation to 'text-mode' and 'prog-mode'

- evil-surround.el
Hi!
I am investigating if we could add this package to [NonGNU ELPA](http://elpa.nongnu.org/) (see link), a new Emacs Lisp package archive that will be enabled by default in Emacs 28. This means that users of that version or later will be able to install this package without any configuration: they can just run `M-x list-packages` and install it out of the box. We hope that this will improve Emacs and help bring new users to this package and others.
1. NonGNU ELPA has a requirement that all files must have a clear statement of its license. I believe the first patch here would be sufficient to fulfill this requirement.
2. The main difference between NonGNU ELPA and MELPA is that only stable versions of packages are released. A new release will be made automatically when you bump the ";; …
> NonGNU ELPA fixes: license statement + bump version

- readme.org
I was looking up the keybindings in the readme and noticed a few small grammar issues, so here's a quick fix for them.
> Fix some grammar quirks in readme.org
